import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Script from "next/script";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Circadian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        type="module"
        src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
      ></Script>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Circadian</h1>

        <p className={styles.description}>
          The Crypto Derived Stock Market
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <p>
              Provide a 24/7, unregulated, no-delay trading platform where users
              around the world can avoid the problems of online brokerages and
              gain greater accessibility to the stock market by using crypto to
              become involved with market trends.
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
          <figure>
            <model-viewer
              style={{ width: "350px", height: "550px" }}
              loading="eager"
              auto-rotate-delay="1000"
              camera-orbit="0 80deg 0"
              interaction-prompt="none"
              rotation-per-second="200%"
              camera-controls
              auto-rotate
              environment-image="neutral"
              disable-zoom
              shadow-intensity="0.6"
              src="../blockO.glb"
            ></model-viewer>
          </figure>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="/" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
